use_frameworks!

platform :ios, '10.0'

target 'InjectionIIISupport_Example' do
  pod 'InjectionIIISupport', :path => '../'

  target 'InjectionIIISupport_Tests' do
    inherit! :search_paths

    
  end
end
